version: '2'
services:
  nginx-proxy:
    image: nginx:stable-alpine
    command: /bin/sh /run.sh
    container_name: 'nginx-proxy'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker-files/www:/www
      - ./docker-files/run.sh:/run.sh
      - ./docker-files/nginx.conf:/etc/nginx/nginx.conf
      - /sites:/sites
      - /tmp/nginx-proxy:/tmp

networks:
  default:
    external:
      name: infra
